import type { XmskMuscleGroup } from '../types'

export const XMSK_MUSCLE_GROUPS: XmskMuscleGroup[] = [
  {
    key: 'shoulder',
    title: '어깨',
    muscles: [
      {
        id: 'shoulder-s1',
        code: 'S1',
        nameKo: '전면삼각근',
        nameEn: 'Anterior Deltoid',
        originInsertion: '쇄골 외측 → 상완골 삼각근 조면',
        action: '굴곡·내회전·수평내전',
        stretch: {
          action: '파지 상완골 원위부·고정 견갑·몸통. 어깨 신전(팔을 뒤로), 견갑 하강 유지.',
          errorResponse: {
            target: '쇄골~어깨 앞 전체 신장감',
            overDone: '상완골 전방활주 → 어깨 앞 찝힘 / 몸통 젖힘 → 요추 보상',
            underDone: '견갑 상승 → 얕게 / 팔 외회전 도망 → 자극 흐림',
            correct: '견갑 하강+상완골만 신전 → 어깨 앞 전체 고른 당김',
          },
        },
        release: {
          position: '앙와위 (어깨 앞이 위)',
          toolIntensity: '손가락 / 손바닥, 중',
          movement: '수축 어깨 굴곡(팔 앞으로) → 이완 어깨 신전(팔 뒤로)',
          caution: '어깨 관절 위를 직접 압박하지 않는다.',
        },
      },
      {
        id: 'shoulder-s2',
        code: 'S2',
        nameKo: '상완이두근',
        nameEn: 'Biceps Brachii',
        originInsertion: '견갑(상결절·오훼돌기) → 요골',
        action: '주관절 굴곡·회외·견관절 굴곡',
        stretch: {
          action: '파지 수근부·고정 전완 원위부. 삼박자 = 회내 + 주관절 신전 + 견관절 신전 (회내가 열쇠).',
          errorResponse: {
            target: '견갑 앞~요골, 상완 앞 전체 신장감',
            overDone: '완전 신전 과압 → 팔꿈치 앞 스트레스 / 어깨 앞 밀림',
            underDone: '회내 안 함 → 회외 기능 안 끊겨 얕게(본인은 착각)',
            correct: '삼박자 동시 → 견갑 앞부터 상완 앞 전체 당김',
          },
        },
        release: {
          position: '앙와위, 팔 회외(이두 위로)',
          toolIntensity: '단두=이두 내측 / 장두=봉우리, 엄지·손날, 높음',
          movement: '수축 팔꿈치 굴곡+회외 → 이완 팔꿈치 신전+회내(+어깨 신전)',
          caution: '발달·단축 쉬운 근육 — 중간에서 양방향, 트랙션 유지.',
        },
      },
      {
        id: 'shoulder-s3',
        code: 'S3',
        nameKo: '소흉근',
        nameEn: 'Pectoralis Minor',
        originInsertion: '3·4·5 늑골 → 오훼돌기',
        action: '견갑 전인·하강',
        stretch: {
          action: '파지 전완(몸통 옆)·고정 견갑극. 견갑 상방회전 + 후방경사(어깨만으론 안 됨, 견갑이 움직여야).',
          errorResponse: {
            target: '어깨 앞 깊은 곳~겨드랑이 앞 신장감',
            overDone: '어깨 앞 충돌 / 흉추 굴곡으로 도망',
            underDone: '어깨 관절만 움직이고 견갑 고정 → 안 늘어남',
            correct: '견갑 상방회전+후방경사 → 어깨 앞 깊은 곳 당김',
          },
        },
        release: {
          position: '앙와위 + 팔 들어 받쳐 어깨 힘 빼기',
          toolIntensity: '손가락/엄지(측면 진입), 중',
          movement: '수축 견갑 전인·하강 → 이완 견갑 후방경사·상방회전',
          caution: '정면 대흉근 뚫지 말고 측면(대흉근-갈비뼈 사이) 진입 · 저림 시 뺌.',
        },
      },
      {
        id: 'shoulder-s4',
        code: 'S4',
        nameKo: '대흉근',
        nameEn: 'Pectoralis Major',
        originInsertion: '흉골·쇄골·늑연골 → 상완골 이두근구',
        action: '수평내전·내회전·굴곡',
        stretch: {
          action: '파지 전완·고정 몸통. 팔 높이(낮/중/높)로 섬유 선택, 수평외전(팔 뒤로 열기). 손목은 방향만, 장력은 몸통에서.',
          errorResponse: {
            target: '쇄골 아래~겨드랑이 앞, 가슴 앞 신장감',
            overDone: '손목 파지 과다 → 어깨 외회전 찝힘',
            underDone: '자극이 어깨 전면에서 끝남 → 흉골까지 안 감(얕음)',
            correct: '가슴(흉골)이 열리는 게 보임 → 가슴 앞 전체 당김',
          },
        },
        release: {
          position: '앙와위, 팔 살짝 외전',
          toolIntensity: '손바닥/척골, 중~높(중앙 예민)',
          movement: '수축 수평내전(팔 가슴 앞으로) → 이완 수평외전(팔 뒤로 열기)',
          caution: '겨드랑이 앞벽 신경·혈관 — 저림 시 즉시 위치 이동.',
        },
      },
      {
        id: 'shoulder-s5',
        code: 'S5',
        nameKo: '후면삼각근',
        nameEn: 'Posterior Deltoid',
        originInsertion: '견갑극 하단 → 상완골 삼각근 조면',
        action: '수평외전·신전·외회전',
        stretch: {
          action: '파지 상완·고정 몸통. 수평내전(팔을 반대쪽 어깨로 cross-body). 대흉근의 길항.',
          errorResponse: {
            target: '어깨 뒤쪽 신장감',
            overDone: '견갑이 팔 따라 딸려감 / 몸통 회전 도망',
            underDone: '어깨 위로 올라감 → 얕게',
            correct: '어깨만 수평내전(cross-body) → 어깨 뒤 당김',
          },
        },
        release: {
          position: '측와위 또는 앙와위(팔 가로질러)',
          toolIntensity: '손가락/엄지, 중',
          movement: '수축 어깨 신전·수평외전(팔 뒤로) → 이완 수평내전(cross-body)',
        },
      },
      {
        id: 'shoulder-s6',
        code: 'S6',
        nameKo: '대원근',
        nameEn: 'Teres Major',
        originInsertion: '견갑골 하각 → 상완골 이두근구',
        action: '신전·내전·내회전',
        stretch: {
          action: "파지 전완·고정 견갑 하각(가볍게). 상완골 굴곡(만세)+외회전. '작은 광배근'.",
          errorResponse: {
            target: '겨드랑이 뒤 아래 신장감',
            overDone: '하각 너무 강하게·먼저 고정 → 굴곡 방해',
            underDone: '외회전 안 줌 → 얕게',
            correct: '만세(굴곡)+외회전 → 겨드랑이 뒤 아래 당김',
          },
        },
        release: {
          position: '측와위(겨드랑이 뒤 접근) 또는 앙와위 팔 들어',
          toolIntensity: '엄지/손가락(쥐어짜기), 중',
          movement: '수축 어깨 신전·내회전 → 이완 어깨 굴곡·외회전(만세+바깥)',
          caution: '광배근과 함께 겨드랑이 뒤벽에서 잡힌다.',
        },
      },
      {
        id: 'shoulder-s7',
        code: 'S7',
        nameKo: '상완삼두근',
        nameEn: 'Triceps Brachii',
        originInsertion: '관절하결절·상완골 후면 → 척골 주두',
        action: '견관절·주관절 신전',
        stretch: {
          action: '파지 상완 원위부·고정 몸통. 어깨 굴곡·외전(만세)+팔꿈치 굴곡. 두 관절.',
          errorResponse: {
            target: '상완 뒤~어깨 뒤 신장감',
            overDone: '몸통 측면 굴곡 도망 / 어깨 충돌',
            underDone: '견갑 먼저 상승 → 얕게',
            correct: '만세+팔꿈치 굴곡 → 상완 뒤 전체 당김',
          },
        },
        release: {
          position: '앙와위 — 팔 감싸 쥐어짜기(추천)',
          toolIntensity: '두 손가락/손바닥(grip), 중~높',
          movement: '수축 팔꿈치 신전 → 이완 팔꿈치 굴곡(+어깨 굴곡)',
          caution: '팔꿈치 안쪽 뒤 척골신경구는 피한다(손 저림).',
        },
      },
      {
        id: 'shoulder-s8',
        code: 'S8',
        nameKo: '광배근',
        nameEn: 'Latissimus Dorsi',
        originInsertion: '흉요추·흉요근막·장골능 → 상완골 이두근구',
        action: '신전·내전·내회전',
        stretch: {
          action: '파지 전완(양손)·고정 동측 다리. 만세(굴곡+외전+외회전). 아래(다리)를 묶어야 위가 늘어남.',
          errorResponse: {
            target: '옆구리~겨드랑이~허리 신장감',
            overDone: '과도한 견갑 상승 / 몸통 회전·굽힘 도망',
            underDone: '하체 무게 안 실림 → 얕게',
            correct: '만세+다리 고정 → 옆구리 긴 라인 전체 당김',
          },
        },
        release: {
          position: '측와위(옆구리 노출)',
          toolIntensity: '손바닥/척골(넓음), 중',
          movement: '수축 어깨 신전·내전(팔 몸통 옆) → 이완 어깨 굴곡·외전(만세)',
        },
      },
    ],
  },
  {
    key: 'neck',
    title: '목',
    safetyNote:
      '경동맥동(SCM 안쪽)·추골동맥(후두하)·상완신경총(사각근 아래) = 강압 금지 구역. 세게·빠르게 금지 · 좌우 동시 금지(경동맥) · 저림·어지럼·시야 흐림 시 즉시 중단.',
    muscles: [
      {
        id: 'neck-n1',
        code: 'N1',
        nameKo: '상부 승모근',
        nameEn: 'Upper Trapezius',
        originInsertion: '후두골·항인대 → 쇄골·견봉',
        action: '견갑 거상·경추 신전·측굴',
        stretch: {
          action: '파지 머리·고정 어깨(하강). 머리를 반대쪽으로 측굴+어깨 하강. 대각선 앞으로.',
          errorResponse: {
            target: '목~어깨선 신장감',
            overDone: '어깨 따라 올라감 → 신장 샘 / 강하게 당김',
            underDone: '어깨 하강 안 함 → 얕게',
            correct: '어깨 하강 고정+반대측 측굴 → 목~어깨선 당김',
          },
        },
        release: {
          position: '앙와위, 머리 반대쪽으로 기울여 진입',
          toolIntensity: '손가락/손바닥(쥐어짜기), 중',
          movement: '수축 동측 측굴+어깨 거상 → 이완 반대측 측굴+어깨 하강',
          caution: '비교적 안전하나 서서히.',
        },
      },
      {
        id: 'neck-n2',
        code: 'N2',
        nameKo: '견갑거근',
        nameEn: 'Levator Scapulae',
        originInsertion: 'C1~C4 횡돌기 → 견갑골 상각',
        action: '견갑 거상·경추 동측 측굴·회전',
        stretch: {
          action: '파지 머리·고정 견갑(하강). 머리를 반대쪽 아래(굴곡+회전)로. 코를 겨드랑이 쪽.',
          errorResponse: {
            target: '목뒤~견갑 상각 신장감',
            overDone: '견갑 따라 올라감 / 강하게',
            underDone: '회전 안 줌 → 얕게',
            correct: '견갑 하강+반대측 굴곡·회전 → 목뒤~상각 당김',
          },
        },
        release: {
          position: '앙와위 또는 측와위, 머리 반대쪽으로 돌림',
          toolIntensity: '엄지/손가락, 중',
          movement: '수축 동측 측굴·회전+견갑 거상 → 이완 반대측 굴곡·회전+견갑 하강',
          caution: '횡돌기(기시) 가까이 목 옆 깊이 강압 금지 — 표층 부착부까지만.',
        },
      },
      {
        id: 'neck-n3',
        code: 'N3',
        nameKo: '흉쇄유돌근',
        nameEn: 'SCM',
        originInsertion: '흉골·쇄골 → 유양돌기',
        action: '반대측 회전·동측 측굴·굴곡',
        stretch: {
          action: '파지 머리·고정 흉골. 신전+반대측 회전+반대측 측굴. 앞목이 늘어남. 경동맥동 주의.',
          errorResponse: {
            target: '앞목~빗장뼈 위 신장감',
            overDone: '앞목(SCM 안쪽) 강압 → 경동맥동 위험 / 신전+회전 강하게',
            underDone: '회전·측굴 안 줌 → 얕게',
            correct: '신전+반대측 회전·측굴 → 앞목이 부드럽게 당김',
          },
        },
        release: {
          position: '앙와위, 머리 반대쪽으로 회전(SCM 도드라짐)',
          toolIntensity: '엄지+검지(집기 pinch), 약~중',
          movement: '수축 반대측 회전+동측 측굴 → 이완 반대 방향으로 회전·측굴',
          caution: '바닥으로 누르기 금지(집기만) · 좌우 동시 절대 금지 · 어지럼·메스꺼움 시 즉시 중단.',
        },
      },
      {
        id: 'neck-n4',
        code: 'N4',
        nameKo: '사각근',
        nameEn: 'Scalenes',
        originInsertion: '경추 횡돌기 → 1·2번 늑골',
        action: '경추 측굴·굴곡 보조·호흡 보조',
        stretch: {
          action: '파지 머리·고정 늑골·어깨. 신전+반대측 측굴. 아래 상완신경총·쇄골하동맥 주의.',
          errorResponse: {
            target: '목 옆~빗장뼈 위 신장감',
            overDone: '사각근부 과압·과신장 → 팔 저림(상완신경총)',
            underDone: '측굴 부족 → 얕게',
            correct: '신전+반대측 측굴 → 목 옆이 부드럽게 당김',
          },
        },
        release: {
          position: '앙와위',
          toolIntensity: '엄지/손가락, 약~중(가볍게)',
          movement: '수축 동측 측굴 → 이완 반대측 측굴+약간 신전',
          caution: '사각근 아래 상완신경총·쇄골하동맥 — 팔 저림 나오면 즉시 감량·중단.',
        },
      },
    ],
  },
  {
    key: 'trunk',
    title: '몸통 (상부)',
    muscles: [
      {
        id: 'trunk-t1',
        code: 'T1',
        nameKo: '능형근',
        nameEn: 'Rhomboids',
        originInsertion: 'C7~T5 극돌기 → 견갑골 내측연',
        action: '견갑 후인·상방',
        stretch: {
          action: '파지 팔·고정 몸통. 견갑 전인(팔을 앞으로 뻗어 날개뼈 벌리기)로 늘림. 라운드숄더선 약해지기 쉬움.',
          errorResponse: {
            target: '날개뼈 사이 신장감',
            overDone: '몸통 회전으로 도망',
            underDone: '견갑 전인 부족 → 날개뼈 안 벌어짐',
            correct: '견갑 전인 → 날개뼈 사이 당김',
          },
        },
        release: {
          position: '복와위 또는 측와위',
          toolIntensity: '엄지/척골, 중',
          movement: '수축 견갑 후인(모으기) → 이완 견갑 전인(벌리기)',
          caution: '약해지기 쉬운 근육 — 이완 후 가볍게 활성 권장.',
        },
      },
      {
        id: 'trunk-t2',
        code: 'T2',
        nameKo: '중·하부 승모근',
        nameEn: 'Mid & Lower Trapezius',
        originInsertion: 'T1~T12 극돌기 → 견갑극·견봉',
        action: '견갑 후인·하강',
        stretch: {
          action: '파지 팔·고정 몸통. 견갑 전인·거상으로 늘림. 자세 유지근이라 약해지기 쉬움.',
          errorResponse: {
            target: '날개뼈 안쪽~아래 신장감',
            overDone: '과도한 몸통 움직임',
            underDone: '견갑 방향 안 맞음 → 얕게',
            correct: '견갑 전인·거상 → 날개뼈 안쪽~아래 당김',
          },
        },
        release: {
          position: '복와위',
          toolIntensity: '손바닥/척골, 중',
          movement: '수축 견갑 후인·하강 → 이완 견갑 전인·거상',
          caution: '자세 유지근 — 이완보다 가볍게 활성이 중심.',
        },
      },
      {
        id: 'trunk-t3',
        code: 'T3',
        nameKo: '척추기립근 (흉추부)',
        nameEn: 'Erector Spinae',
        originInsertion: '천골·장골능 → 늑골·횡돌기',
        action: '척추 신전',
        stretch: {
          action: '파지·고정 골반. 흉추 굴곡(등 둥글게 말기)로 늘림. 극돌기가 아니라 양옆 세로 근육.',
          errorResponse: {
            target: '등 뒤 세로 라인 신장감',
            overDone: '요추까지 과굴곡 보상',
            underDone: '흉추만 안 말림 → 얕게',
            correct: '흉추 굴곡 → 등 뒤 세로 라인 당김',
          },
        },
        release: {
          position: '복와위',
          toolIntensity: '엄지/척골(세로로), 중',
          movement: '수축 척추 신전(살짝 젖힘) → 이완 척추 굴곡(둥글게)',
          caution: '극돌기(가운데 뼈) 직접 압박 금지 · 요추는 안정 영역.',
        },
      },
      {
        id: 'trunk-t4',
        code: 'T4',
        nameKo: '흉추 표층 (다열근 위)',
        nameEn: 'Thoracic Paraspinals',
        originInsertion: '흉추 분절 주변 표층',
        action: '분절 신전·회전 보조',
        stretch: {
          action: '파지·고정 골반. 흉추 회전·굴곡으로 늘림. 심부 다열근은 활성 대상이라 제외.',
          errorResponse: {
            target: '흉추 분절 주변 신장감',
            overDone: '과한 회전으로 요추 보상',
            underDone: '분절 안 움직임 → 얕게',
            correct: '분절 굴곡·회전 → 흉추 주변 당김',
          },
        },
        release: {
          position: '복와위',
          toolIntensity: '엄지, 약~중',
          movement: '수축 해당 분절 신전 → 이완 분절 굴곡·회전',
          caution: '심부 다열근은 이완하지 않는다(활성 대상) · 호흡(호기)에 맞춰 표층만.',
        },
      },
    ],
  },
  {
    key: 'hip',
    title: '고관절',
    muscles: [
      {
        id: 'hip-h1',
        code: 'H1',
        nameKo: '장요근',
        nameEn: 'Iliopsoas',
        originInsertion: '요추·장골 내면 → 대퇴골 소전자',
        action: '고관절 굴곡',
        stretch: {
          action: '파지 수근부·고정 골반. 런지로 뒷다리 고관절 신전(작용의 반대). 요추가 꺾이지 않게.',
          errorResponse: {
            target: '고관절 앞~하복부 심부 신장감',
            overDone: '요추 과신전으로 도망 → 허리 꺾임·요추 보상',
            underDone: '고관절만 얕게 신전 → 심부까지 안 늘어남',
            correct: '골반 중립 유지한 채 고관절 신전 → 고관절 앞이 깊게 당김',
          },
        },
        release: {
          position: '앙와위, 무릎 세워 복부 이완',
          toolIntensity: '손가락, 약~중(서서히)',
          movement: '수축 고관절 굴곡(무릎을 배로) → 이완 고관절 신전(다리 내림)',
          caution: '복부 대혈관·장기 인접 — 박동 느껴지면 즉시 위치 이동. 매우 신중히.',
        },
      },
      {
        id: 'hip-h2',
        code: 'H2',
        nameKo: '둔근 (대·중둔근)',
        nameEn: 'Gluteus',
        originInsertion: '천골·장골 후방 → 대퇴골·장경인대',
        action: '신전·외전·회전',
        stretch: {
          action: '파지 무릎·고정 반대 골반. 누워 무릎을 반대편 가슴으로(굴곡+내전). 회전 조절로 부위 이동.',
          errorResponse: {
            target: '엉덩이 뒤 전체 신장감',
            overDone: '요추가 굽어 도망 → 요추 굴곡 보상',
            underDone: '회전 안 줌 → 특정 섬유만 얕게',
            correct: '굴곡+내전에 회전 조절 → 엉덩이 뒤가 고르게 당김',
          },
        },
        release: {
          position: '복와위 또는 측와위',
          toolIntensity: '척골 / 팔꿈치(두꺼움), 중~높',
          movement: '수축 고관절 신전·외전 → 이완 고관절 굴곡·내전',
          caution: '내전근 자극과 구분 — 넓게 여러 방향으로.',
        },
      },
      {
        id: 'hip-h3',
        code: 'H3',
        nameKo: '이상근',
        nameEn: 'Piriformis',
        originInsertion: '천골 전면 → 대퇴골 대전자',
        action: '외회전 (굴곡 시 내회전)',
        stretch: {
          action: '파지 무릎·고정 골반. 무릎 굽혀 반대편으로 넘김. 좌골신경 인접 — 저림 시 범위 축소.',
          errorResponse: {
            target: '엉덩이 깊은 곳 신장감',
            overDone: '저림·방사통 무시하고 진행 → 좌골신경 자극',
            underDone: '굴곡 부족 → 심부 외회전근에 안 닿음',
            correct: '충분히 굴곡시킨 뒤 회전 결합 → 엉덩이 심부 당김, 저림 없음',
          },
        },
        release: {
          position: '복와위, 무릎 굽혀 하퇴 안팎으로 눕히며 회전',
          toolIntensity: '엄지 / 팔꿈치, 중',
          movement: '수축 고관절 외회전 → 이완 고관절 내회전',
          caution: '좌골신경 인접(또는 관통) — 다리로 방사되는 저림 시 즉시 강도↓·중단.',
        },
      },
      {
        id: 'hip-h4',
        code: 'H4',
        nameKo: '내전근',
        nameEn: 'Adductors',
        originInsertion: '치골·좌골 → 대퇴골 조선·경골 내측(박근)',
        action: '고관절 내전',
        stretch: {
          action: '파지 발바닥·고정 대퇴. 다리 외전(벌림)+무릎 신전. 박근이 무릎 건너므로 무릎 펴야 전체가 늘어남.',
          errorResponse: {
            target: '허벅지 안쪽 전체 신장감',
            overDone: '외전만 급하게 크게 → 사타구니 통증',
            underDone: '무릎 굽힘 → 박근 느슨해 얕게 끝남',
            correct: '무릎 펴고 외전 → 허벅지 안쪽 긴 라인 전체 당김',
          },
        },
        release: {
          position: '앙와위, 다리 살짝 외전·외회전(벌려 눕힘)',
          toolIntensity: '손바닥 / 척골, 중',
          movement: '수축 고관절 내전(다리 모음) → 이완 고관절 외전(다리 벌림)',
          caution: '허벅지 안쪽 상부 깊은 곳(대퇴 삼각)은 신경·혈관 — 강압 금지.',
        },
      },
      {
        id: 'hip-h5',
        code: 'H5',
        nameKo: '대퇴근막장근 (TFL)',
        nameEn: 'Tensor Fasciae Latae',
        originInsertion: 'ASIS·장골능 → 장경인대',
        action: '고관절 굴곡·외전·내회전',
        stretch: {
          action: '파지 대퇴·고정 골반. 고관절 내전+외회전으로 외측 라인 신장. 장경인대 통해 무릎 바깥까지.',
          errorResponse: {
            target: '고관절 앞바깥~허벅지 외측 신장감',
            overDone: '골반 과회전 허용 → 골반 보상',
            underDone: '내전·외회전 부족 → 외측 라인에 안 걸림',
            correct: '고관절 내전+외회전 → 앞바깥~외측 라인 당김',
          },
        },
        release: {
          position: '측와위(위쪽 다리)',
          toolIntensity: '엄지 / 손가락, 중',
          movement: '수축 고관절 굴곡·외전·내회전 → 이완 고관절 신전·내전',
          caution: '무릎 외측 전달 자극 주의.',
        },
      },
    ],
  },
  {
    key: 'knee',
    title: '무릎',
    muscles: [
      {
        id: 'knee-k1',
        code: 'K1',
        nameKo: '대퇴사두근',
        nameEn: 'Quadriceps',
        originInsertion: '장골·대퇴골 → 경골조면',
        action: '무릎 신전 (대퇴직근은 고관절 굴곡)',
        stretch: {
          action: '파지 발목·고정 골반. 뒤꿈치를 엉덩이로(무릎 굴곡)+고관절 신전. 대퇴직근까지 늘리려면 신전 결합.',
          errorResponse: {
            target: '허벅지 앞 전체 신장감',
            overDone: '요추 과신전 보상 / 무릎 과압',
            underDone: '무릎만 굽힘 → 대퇴직근 안 늘어남',
            correct: '무릎 굴곡+고관절 신전 → 허벅지 앞 전체 당김',
          },
        },
        release: {
          position: '앙와위 (허벅지 앞이 위)',
          toolIntensity: '손바닥 / 척골 / 팔꿈치, 중~높',
          movement: '수축 무릎 신전 → 이완 무릎 굴곡(+고관절 신전)',
          caution: '슬개골(정지 힘줄)은 세게 누르지 않는다.',
        },
      },
      {
        id: 'knee-k2',
        code: 'K2',
        nameKo: '햄스트링',
        nameEn: 'Hamstring',
        originInsertion: '좌골결절 → 경골 내측·비골두',
        action: '고관절 신전·무릎 굴곡',
        stretch: {
          action: '파지 종골·고정 대퇴. 무릎 펴고 고관절 굴곡. 골반 후방경사로 말리지 않게.',
          errorResponse: {
            target: '엉덩이 밑~무릎 뒤 전체 신장감',
            overDone: '골반 후방경사로 말림 → 요추 보상',
            underDone: '무릎 굽힘 → 얕게 끝남',
            correct: '무릎 펴고 고관절 굴곡, 골반 정렬 유지 → 뒤 라인 전체 당김',
          },
        },
        release: {
          position: '복와위 (허벅지 뒤가 위)',
          toolIntensity: '척골 / 손바닥 / 팔꿈치, 중~높',
          movement: '수축 무릎 굴곡 → 이완 무릎 신전(+고관절 굴곡)',
          caution: '오금(슬와부)은 신경·혈관 밀집 — 직접 강압 금지.',
        },
      },
      {
        id: 'knee-k3',
        code: 'K3',
        nameKo: '거위발건 (봉공·박근·반건양)',
        nameEn: 'Pes Anserinus',
        originInsertion: '봉공(장골)·박근(치골)·반건양(좌골) → 경골 내측',
        action: '세 근육 모두 무릎 굴곡에 관여',
        stretch: {
          action: '무릎 안쪽 경골 내측에 세 힘줄이 모임. 각 근육 방향으로 늘림. 무릎 펴서 공통 신장.',
          errorResponse: {
            target: '무릎 안쪽~허벅지 안·뒤 신장감',
            overDone: '무릎 안쪽 과압 → 거위발건 자극 통증',
            underDone: '무릎 굽힘 → 세 근육 다 느슨',
            correct: '무릎 펴고 각 근육 방향 결합 → 무릎 안쪽 라인 당김',
          },
        },
        release: {
          position: '앙와위 또는 측와위, 무릎 안쪽 노출',
          toolIntensity: '엄지 / 손가락, 중',
          movement: '수축 무릎 굴곡 → 이완 무릎 신전',
          caution: '공유 부착점 — 무릎 안쪽 통증(거위발건염) 시 강압 금지, 순환 위주.',
        },
      },
    ],
  },
  {
    key: 'foot',
    title: '발·발목',
    muscles: [
      {
        id: 'foot-f1',
        code: 'F1',
        nameKo: '비복근',
        nameEn: 'Gastrocnemius',
        originInsertion: '대퇴골 내·외측상과 → 종골(아킬레스)',
        action: '무릎 굴곡·발목 저측굴곡',
        stretch: {
          action: '파지 전족부·고정 발목. 무릎 펴고 발목 배측굴곡(발끝 당김). 두 관절 근육이라 무릎 펴야 최대.',
          errorResponse: {
            target: '종아리 위쪽~오금 신장감',
            overDone: '무릎 굽힘 → 신장이 샌다',
            underDone: '발목만 당김 → 얕음',
            correct: '무릎 펴고 발목 배측굴곡 → 종아리 위쪽 당김',
          },
        },
        release: {
          position: '복와위 (종아리 위로)',
          toolIntensity: '손바닥 / 척골(쥐어짜기), 중',
          movement: '수축 발목 저측굴곡+무릎 살짝 굽힘 → 이완 발목 배측굴곡+무릎 폄',
          caution: '아킬레스건(정지)은 세게 쥐지 않는다.',
        },
      },
      {
        id: 'foot-f2',
        code: 'F2',
        nameKo: '가자미근',
        nameEn: 'Soleus',
        originInsertion: '경골·비골 후면 → 종골(아킬레스)',
        action: '발목 저측굴곡 (한 관절)',
        stretch: {
          action: '파지 전족부·고정 발목. 무릎 굽힌 채 발목 배측굴곡. 무릎을 굽혀야 비복근을 빼고 가자미근을 겨냥.',
          errorResponse: {
            target: '종아리 아래·깊은 곳 신장감',
            overDone: '과한 배측굴곡으로 발목 앞 충돌',
            underDone: '무릎 펴고 함 → 비복근만, 가자미근 안 늘어남',
            correct: '무릎 굽히고 발목 배측굴곡 → 종아리 아래 깊은 곳 당김',
          },
        },
        release: {
          position: '복와위, 무릎 굽힘',
          toolIntensity: '엄지 / 척골, 중',
          movement: '수축 발목 저측굴곡 → 이완 발목 배측굴곡(무릎 굽힌 채)',
          caution: '아킬레스 이행부 강압 주의.',
        },
      },
      {
        id: 'foot-f3',
        code: 'F3',
        nameKo: '전경골근',
        nameEn: 'Tibialis Anterior',
        originInsertion: '경골 외측·골간막 → 제1중족골·내측설상골',
        action: '발목 배측굴곡·내번',
        stretch: {
          action: '파지 발등·고정 발목. 발목 저측굴곡(발끝 펴기)+약간 외번. 작용의 반대.',
          errorResponse: {
            target: '정강이 앞바깥 신장감',
            overDone: '급한 저측굴곡 → 발등 힘줄부 부담',
            underDone: '외번 안 줌 → 얕음',
            correct: '저측굴곡+약간 외번 → 정강이 앞바깥 당김',
          },
        },
        release: {
          position: '앙와위',
          toolIntensity: '엄지 / 손날, 중',
          movement: '수축 발목 배측굴곡 → 이완 발목 저측굴곡',
          caution: '발등 힘줄부 압박 주의.',
        },
      },
      {
        id: 'foot-f4',
        code: 'F4',
        nameKo: '후경골근·비골근',
        nameEn: 'Tib. Post. · Peroneus',
        originInsertion: '경골·비골 후면 / 비골 → 발 안쪽·바깥',
        action: '아치·발목 좌우 안정',
        stretch: {
          action: '후경골근=배측굴곡+외번으로 늘림 / 비골근=내번+배측굴곡으로 늘림. 발목 좌우 안정근.',
          errorResponse: {
            target: '종아리 안쪽(후경골)·바깥(비골) 신장감',
            overDone: '급한 반대 방향 → 발목 인대 스트레스',
            underDone: '방향 안 맞음 → 자극 흐림',
            correct: '각 근육의 반대 방향으로 → 해당 측 당김',
          },
        },
        release: {
          position: '측와위 또는 앙와위',
          toolIntensity: '엄지, 중(가볍게)',
          movement: '수축 각 근육 작용 방향(내번/외번) → 이완 반대 방향',
          caution: "자주 삐는 발목엔 '가볍게 깨우는' 목적 — 해결이 아니라 다른 가동 개선 보조.",
        },
      },
      {
        id: 'foot-f5',
        code: 'F5',
        nameKo: '아킬레스건·족저 이행부',
        nameEn: 'Achilles',
        originInsertion: '비복·가자미 → 종골',
        action: '발목 저측굴곡 힘 전달',
        stretch: {
          action: '건 자체는 늘리지 않고, 위(비복·가자미) 이완으로 장력을 던다. 상태 체크가 먼저.',
          errorResponse: {
            target: '뒤꿈치 뒤~종아리 연결 부드러움',
            overDone: '급성 염증·파열 의심에 강압 → 악화',
            underDone: '건만 만지고 위 근육 안 풂 → 장력 그대로',
            correct: '비복·가자미를 풀어 아킬레스 장력이 내려감',
          },
        },
        release: {
          position: '복와위',
          toolIntensity: '엄지·손가락(건 주변만), 약',
          movement: '수축 발목 저측굴곡 → 이완 발목 배측굴곡',
          caution: '상태 체크 필수 — 꼬집어 비틀기·뒤꿈치 압박으로 통증 확인. 파열음+발끝 못 섬 → 즉시 의뢰.',
        },
      },
    ],
  },
  {
    key: 'toe',
    title: '발가락·발바닥',
    muscles: [
      {
        id: 'toe-t1',
        code: 'T1',
        nameKo: '발가락 관절',
        nameEn: 'Toe Joints',
        originInsertion: '족지 굴곡·신전근·내재근',
        action: '발가락 굴곡·신전·외전',
        stretch: {
          action: '발가락을 발등 쪽으로 젖힘(신전)+발목 배측굴곡 결합해 족저근막까지. 이어서 오므리고·부챗살로 벌려 개별 관절 가동.',
          errorResponse: {
            target: '발바닥~발가락 바닥 전체 신장감',
            overDone: '한 발가락만 과하게 젖힘 → 관절 스트레스',
            underDone: '발가락만 젖히고 발목 안 씀 → 족저근막 안 늘어남',
            correct: '발가락 신전+발목 배측굴곡 → 발바닥 전체 당김, 개별 관절도 가동',
          },
        },
        release: {
          position: '앙와위 또는 좌위',
          toolIntensity: '손가락(발가락 모아 잡음), 중',
          movement: '수축 발가락 굴곡(오므림) → 이완 발가락 신전(발등 쪽)',
          caution: '개별 관절은 하나씩 분리해 가동.',
        },
      },
      {
        id: 'toe-t2',
        code: 'T2',
        nameKo: '족저근막',
        nameEn: 'Plantar Fascia',
        originInsertion: '종골 → 중족골·발가락 기저',
        action: '아치 유지·발바닥 장력',
        stretch: {
          action: '근막이완이 메인. 발가락을 신전시켜 근막을 팽팽하게(윈들라스) 한 뒤 뒤꿈치→발가락 방향으로 결 따라.',
          errorResponse: {
            target: '발바닥 아치 세로 라인 신장감',
            overDone: '급성 염증(아침 첫발 극심)에 강압 → 악화',
            underDone: '근막 느슨한 채 누름 → 표면만',
            correct: '발가락 신전으로 팽팽하게 → 결 따라 세로로 풀림',
          },
        },
        release: {
          position: '앙와위(발바닥이 트레이너 쪽) 또는 좌위',
          toolIntensity: '엄지·손가락 관절(셀프는 공), 중',
          movement: '수축 발가락 굴곡(근막 느슨) → 이완 발가락 신전(근막 팽팽)',
          caution: '아침 첫발 극심·열감·부종이면 강압 금지, 순환 위주.',
        },
      },
      {
        id: 'toe-t3',
        code: 'T3',
        nameKo: '발 내재근',
        nameEn: 'Foot Intrinsics',
        originInsertion: '발바닥 심부 작은 근육들',
        action: '아치 안정·발가락 미세 조절',
        stretch: {
          action: '근막이완 메인. 아치의 도톰한 부위(무지구·소지구)를 발가락 움직이며 촉지해 심부까지.',
          errorResponse: {
            target: '발바닥 심부(표층 족저근막 아래) 반응',
            overDone: '예민한 부위 과압 → 통증',
            underDone: '족저근막(표층)만 풀고 심부 안 감 → 아치 안정 약함',
            correct: '표층 풀고 심부 내재근까지 → 아치 안정 개선',
          },
        },
        release: {
          position: '앙와위 또는 좌위',
          toolIntensity: '엄지, 중',
          movement: '수축 발가락 오므림 → 이완 발가락 폄',
          caution: '발은 체중 받는 예민한 부위 — 세게 뚫지 말고 팽팽하게 만들어 결 따라.',
        },
      },
    ],
  },
]
